name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: false
          tags: myblog:latest

      - name: Run container
        run: |
          docker run -d --name myblog_ci -p 8000:8000 myblog:latest

      - name: Wait for container to be ready
        run: sleep 10

      - name: Execute tests inside container
        run: |
          docker exec myblog_ci pytest -q

      - name: Stop and remove container
        run: docker rm -f myblog_ci